server.port: 9090

# url to lookup the public keys
keySetURI: http://localhost:8080/oauth2/jwks

spring:
  main:
    banner-mode: off

# change client and secret
introspectionUri: http://localhost:8080/oauth2/introspect
clientID: resource-server
clientSecret: resource-server-secret

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: TRACE
    org.springframework.security.oauth2: TRACE