server.port: 9000
spring:
  main:
    banner-mode: off
logging:
  level:
    root: info
    org.springframework.web: info
    org.springframework.security: info
    org.springframework.security.oauth2: info
    org.nahsi.poc.controllers: trace